services:
  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: postgresdatabase
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgresdatabase"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgres_db_data:





