# Generated by Django 5.1.7 on 2025-06-15 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classroom_scheduler",
            "0003_remove_reservationinfo_class_representatives_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="proposed_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposed_reservations",
                to="classroom_scheduler.room",
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="class_representatives",
            field=models.ManyToManyField(
                related_name="representative_of_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="instructed_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="classroom_scheduler.reservationinfo",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="classroom_scheduler.room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_rooms",
                to="classroom_scheduler.equipment",
            ),
        ),
    ]
